title: "My Advanced API Portal"
description: "Developer portal with guides, reference, and reusable components."

appearance:
  theme:
    colors:
      primary: "#32329f"
      secondary: "#ff6600"
    typography:
      fontFamily: "Inter, sans-serif"

navigation:
  - label: Home
    page: pages/index.mdx
  - label: Getting Started
    page: pages/getting-started.mdx
  - label: Authentication
    page: pages/authentication.mdx
  - label: API Reference
    api: sample@v1
  - label: Error Handling
    page: pages/errors.mdx

apis:
  sample@v1:
    root: ./openapi/openapi.yaml
    referenceDocs:
      theme:
        colors:
          primary:
            main: "#32329f"
      generateCodeSamples:
        languages:
          - lang: curl
          - lang: Node.js
          - lang: Python
